{{ if .Values.jobs.accountsPrune.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "mastodon.fullname" . }}-accounts-prune
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.jobs.accountsPrune.schedule }}
  jobTemplate:
    spec:
      template:
        metadata:
          name: {{ include "mastodon.fullname" . }}-accounts-prune
          {{- with .Values.jobs.annotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          restartPolicy: OnFailure
          containers:
            - name: accounts-prune
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                - bash
                - -c
                - "bin/tootctl accounts prune"
              envFrom:
                - configMapRef:
                    name: {{ include "mastodon.fullname" . }}-env
                - secretRef:
                    name: {{ include "mastodon.fullname" . }}-secrets-env
              env:
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      key: {{ .Values.configuration.database.credentialSecret.usernameKey }}
                      name: {{ .Values.configuration.database.credentialSecret.name }}
                - name: DB_PASS
                  valueFrom:
                    secretKeyRef:
                      key: {{ .Values.configuration.database.credentialSecret.passwordKey }}
                      name: {{ .Values.configuration.database.credentialSecret.name }}
                {{- if .Values.configuration.redis.separateCache.enabled | default false }}
                - name: CACHE_REDIS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: {{ .Values.configuration.redis.separateCache.authSecretKey }}
                      name: {{ .Values.configuration.redis.separateCache.authSecretName }}
                {{- end }}
              resources:
                {{- toYaml .Values.jobs.accountsPrune.resources | nindent 16 }}
{{ end }}
