{{- $fullName := include "mastodon.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.ingress.maxBodySize }}
    nginx.ingress.kubernetes.io/client-body-buffer-size: {{ .Values.ingress.maxBodySize }}
    nginx.ingress.kubernetes.io/proxy-connect-timeout: {{ .Values.ingress.upstreamProxyTimeout | quote }}
    nginx.ingress.kubernetes.io/proxy-read-timeout: {{ .Values.ingress.upstreamProxyTimeout | quote }}
    nginx.ingress.kubernetes.io/proxy-send-timeout: {{ .Values.ingress.upstreamProxyTimeout | quote }}
    cert-manager.io/cluster-issuer: letsencrypt-prod
    {{- if .Values.ingress.verifyClient.enabled }}
    nginx.ingress.kubernetes.io/auth-tls-secret: {{ .Values.ingress.verifyClient.secretName }}
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "false"
    {{- end }}
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
  name: {{ $fullName }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "mastodon.fullname" . }}-web
                port:
                  number: 3000
            path: /
            pathType: ImplementationSpecific
          - backend:
              service:
                name: {{ include "mastodon.fullname" . }}-streaming
                port:
                  number: 4000
            path: /api/v1/streaming
            pathType: ImplementationSpecific
          {{- if .Values.web.primaryDatabaseDeployment }}
          {{- if .Values.web.primaryDatabaseDeployment.enabled }}
          - backend:
              service:
                name: {{ include "mastodon.fullname" . }}-web-primary-db
                port:
                  number: 3000
            path: /oauth
            pathType: ImplementationSpecific
          - backend:
              service:
                name: {{ include "mastodon.fullname" . }}-web-primary-db
                port:
                  number: 3000
            path: /api/v1/accounts/verify_credentials
            pathType: ImplementationSpecific
          {{- end }}
          {{- end }}
  tls:
    {{ .Values.ingress.tls | toYaml | nindent 4 }}
