{{- $fullName := include "mastodon.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 40m
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
  name: {{ $fullName }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "mastodon.fullname" . }}-web
                port:
                  number: 3000
            path: /
            pathType: ImplementationSpecific
          - backend:
              service:
                name: {{ include "mastodon.fullname" . }}-streaming
                port:
                  number: 4000
            path: /api/v1/streaming
            pathType: ImplementationSpecific
  tls:
    {{ .Values.ingress.tls | toYaml | nindent 4 }}
