{{ if .Values.streaming.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "mastodon.fullname" . }}-streaming
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: streaming
  podMetricsEndpoints:
    - port: {{ .Values.streaming.podMonitor.port }}
      interval: {{ .Values.streaming.podMonitor.interval }}
      scrapeTimeout: {{ .Values.streaming.podMonitor.scrapeTimeout }}
      path: {{ .Values.streaming.podMonitor.path }}
      scheme: {{ .Values.streaming.podMonitor.scheme }}
{{ end }}
