{{- $context := . }}
{{- range .Values.sidekiq.workers }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "mastodon.fullname" $context }}-sidekiq-{{ .name }}
  {{- include "mastodon.labels" $context | nindent 4 }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       {{ include "mastodon.fullname" $context }}-sidekiq-{{ .name }}
  updatePolicy:
    updateMode: "Off"
{{- end }}
