apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/configuration-snippet: |
      return 200 "36a0b8bf5e36ebb164f5c25c33843249a2d89d314b30f4653c46bc0a74f8a9e0\n19bdf56f6616aa45178dc9b1779d6e4712d32cbd23d3cdae50738b1121cc0fc7";
  name: fluent-bit-fastly-verify
  namespace: fluentbit
spec:
  ingressClassName: nginx
  rules:
  - host: fluent-bit.toot.community
    http:
      paths:
      - backend:
          service:
            name: fluent-bit
            port:
              number: 2020
        path: /.well-known/fastly/logging/challenge
        pathType: Prefix
  tls:
  - hosts:
    - fluent-bit.toot.community
    secretName: fluent-bit.toot.community-tls
