apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-loki
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: loki
        type: loki
        url: "http://loki-gateway.loki.svc.cluster.local"
        jsonData:
          httpHeaderName1: 'X-Scope-OrgID'
          timeout: "900"
        secureJsonData:
          httpHeaderValue1: 'tootcommunity'
