apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: tootcommunity-db-pooler-rw
  namespace: tootcommunity
spec:
  cluster:
    name: tootcommunity-db
  instances: 2
  type: rw
  pgbouncer:
    poolMode: transaction
    parameters:
      max_client_conn: "1000"
      default_pool_size: "145"
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: doks.digitalocean.com/node-pool
                    operator: In
                    values:
                      - pool-db-3
      containers: []
      tolerations:
        - effect: NoSchedule
          key: limit
          operator: Equal
          value: db
