apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: esb
    meta.helm.sh/release-namespace: esb
  labels:
    app.kubernetes.io/instance: esb
    app.kubernetes.io/name: n8n
  name: n8n
  namespace: esb
