apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleanup-preview-cards
  namespace: mastodon
  labels:
    app.kubernetes.io/component: cronjob-cleanup-media-cards
    app.kubernetes.io/instance: mastodon
    app.kubernetes.io/name: cronjob-cleanup-media-cards
spec:
  schedule: "0 6 * * 1" # At 05:00 on Monday.
  jobTemplate:
    spec:
      template:
        metadata:
          name: cleanup-preview-cards
        spec:
          restartPolicy: OnFailure
          containers:
            - name: cleanup-media-cards
              image: tootsuite/mastodon:v4.0.2
              imagePullPolicy: IfNotPresent
              command:
                - bash
                - -c
                - "bin/tootctl preview_cards remove"
              envFrom:
                - configMapRef:
                    name: mastodon-env
                - secretRef:
                    name: mastodon-secrets-env
              resources:
                requests:
                  cpu: 500m
                  memory: 250Mi
