apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    app.kubernetes.io/component: streaming
    app.kubernetes.io/instance: mastodon
    app.kubernetes.io/name: mastodon
  name: mastodon-streaming
  namespace: mastodon
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: streaming
      app.kubernetes.io/instance: mastodon
      app.kubernetes.io/name: mastodon
