apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    app.kubernetes.io/component: web
    app.kubernetes.io/instance: mastodon
    app.kubernetes.io/name: mastodon
    app.kubernetes.io/part-of: rails
  name: mastodon-web
  namespace: mastodon
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: web
      app.kubernetes.io/instance: mastodon
      app.kubernetes.io/name: mastodon
      app.kubernetes.io/part-of: rails
