apiVersion: v1
data:
  haproxy.cfg: |
    global
      log stdout format raw local0

    defaults
     log global
     timeout connect 5s
     timeout client 1m
     timeout server 1m

    # https://cbonte.github.io/haproxy-dconv/1.7/configuration.html#5.3
    resolvers kube-dns
      parse-resolv-conf
      resolve_retries    30
      timeout retry      1s
      hold valid         1s

    frontend do_redis
      bind :6379
      default_backend do_redis_1

    frontend stats
      mode http
      bind *:8404
      http-request use-service prometheus-exporter if { path /metrics }
      stats enable
      stats uri /stats
      stats refresh 10s

    backend do_redis_1
      server do_redis_1 private-db-redis-ams3-toot-community-do-user-924064-0.b.db.ondigitalocean.com:25061 ssl verify none check inter 1s resolvers kube-dns
kind: ConfigMap
metadata:
  name: do-redis-config
  namespace: haproxy
