apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: mastodon
    meta.helm.sh/release-namespace: mastodon
  labels:
    app.kubernetes.io/instance: haproxy
    app.kubernetes.io/name: do-redis
  name: do-redis
  namespace: haproxy
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  selector:
    app.kubernetes.io/instance: haproxy
    app.kubernetes.io/name: do-redis
