apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentbit-fastly
  namespace: argocd
spec:
  destination:
    namespace: fluentbit
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    path: fluentbit/
    repoURL: git@github.com:toot-community/kubernetes.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
