apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: haproxy
  namespace: argocd
spec:
  destination:
    namespace: haproxy
    server: https://kubernetes.default.svc
  project: mastodon
  source:
    path: haproxy
    repoURL: git@github.com:toot-community/kubernetes.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
