apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
spec:
  destination:
    namespace: keda
    server: https://kubernetes.default.svc
  project: infrastructure
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  source:
    chart: keda
    repoURL: https://kedacore.github.io/charts
    targetRevision: 2.11.1
    helm:
      values: |
        operator:
          replicaCount: 2
        metricsServer:
          replicaCount: 2
        resources:
          operator:
            requests:
              cpu: 5m
              memory: 82M
            limits:
              memory: 82M
          webhooks:
            requests:
              cpu: 5m
              memory: 23M
            limits:
              memory: 23M
          metricServer:
            requests:
              cpu: 5m
              memory: 51M
            limits:
              memory: 51M
