apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-manifests
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: monitoring
  source:
    directory:
      recurse: true
    path: monitoring/
    repoURL: git@github.com:toot-community/kubernetes.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
