apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tootcommunity-search
  namespace: argocd
spec:
  destination:
    namespace: tootcommunity
    server: https://kubernetes.default.svc
  project: mastodon
  source:
    directory:
      recurse: true
    path: elasticsearch
    repoURL: git@github.com:toot-community/kubernetes.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
