apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tootcommunity-db
  namespace: argocd
spec:
  destination:
    namespace: tootcommunity
    server: https://kubernetes.default.svc
  project: mastodon
  source:
    path: databases/postgres/
    repoURL: git@github.com:toot-community/kubernetes.git
    targetRevision: main
