connect:
  api:
    resources:
      requests:
        cpu: 15m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 256Mi
  sync:
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi

operator:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
